
public enum EntityTypeEnum
{
    Building, //Castle, gate etc...
    Turret, //Defensive building etc...
    Walking, //Soldier, Horse etc...
    WalkingAR, //Archer etc...
    Flying, //Gryffon etc...
    FlyingAW //Mounted Gryffon with archer etc...
}
